name: Workflow used for Tests

on:
    workflow_dispatch:


jobs:
    single_stage:
        runs-on: ubuntu-latest

        steps:
            - name: Print something
              run: echo 'Workflow used for API tests'